### PR TITLE
#175636830  Setup sequerizerc

### PR DESCRIPTION
**Pull request by tytyne**
#### What does this PR do?

- The PR setup sequelize in the project

#### Description of Task to be completed?

- creating sequelizerc file 
- creating migrations folder
- creating seeders folder
- creating models folder 

#### How should this be manually tested?

- ` git clone https://github.com/atlp-rwanda/tech-strikers-bn-backend  `

-  `git checkout ch-setup-sequelizerc-175636830`

- `npm install`

- `npm run start`

- `touch .env`

- copy paste what is in  ` .env.example file`

- add your own credentials(username,password,database name)

- ` sequelize db:migrate`   or `./node_modules/.bin/sequelize db:migrate` to do migrations

- `sequelize db:seed:all` to seed database or `./node_modules/.bin/sequelize db:seed:all` to seed database

#### Any background context you want to provide?
no
#### What are the relevant pivotal tracker stories?
[#175636830](https://www.pivotaltracker.com/story/show/175636830)
#### Screenshots (if appropriate)
sequelizerc file
sequelize

### CODE REVIEW

**Review by Duncanwar — COMMENTED** [review]
Fix your commit, make sure there is one author for @Thiernope  PR to be merged?

**Comment by bigelio** [comment]
Looks great @tytyne !

**Comment by kipropbrian** [comment]
Hey, on reviewing this PR, I am getting this error 

```
Sequelize CLI [Node: 14.4.0, CLI: 5.5.0, ORM: 6.3.5]

Loaded configuration file "src/database/config/config.js".
Using environment "development".
Executing (default): SELECT 1+1 AS result
Executing (default): SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type LIKE '%TABLE' AND table_name != 'spatial_ref_sys';
Executing (default): CREATE TABLE IF NOT EXISTS "SequelizeMeta" ("name" VARCHAR(255) NOT NULL UNIQUE , PRIMARY KEY ("name"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'SequelizeMeta' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;

ERROR: array.parse is not a function
```

**Review by kipropbrian — APPROVED** [review]
Good job

**Pull request merged**
