### PR TITLE
#175636837 Setup api documentation with swagger

### PR DESCRIPTION
**Pull request by bigelio**
#### What does this PR do?

Setup api documentation with swagger

#### Description of Task to be completed?

-Added swagger documentations on all routes.
-Added swagger.json file with object that generate documentations.
-Updated README.md file with the link to apis documentation.

#### How should this be manually tested?

run `git clone https://github.com/atlp-rwanda/tech-strikers-bn-backend.git`
run `cd tech-strikers-bn-backend`
run `npm install`
run `npm start`
In your browser navigate to `localhost:3000`

#### What are the relevant pivotal tracker stories?
[#175636837](https://www.pivotaltracker.com/n/projects/2475704)

#### Screenshots (if appropriate)

Screen Shot 2020-11-14 at 16 33 16

### CODE REVIEW

**Review by hervebutera — CHANGES_REQUESTED** [review]
Well done but check under  'How should this be manually tested'  and correct the mistake in command `cd directory ...`  and try to check the conflicting files if it isn't done while merging.

**Review by hervebutera — APPROVED** [review]

**Review by tytyne — COMMENTED** [review]
Can you please add routes screenshots of swagger documentation?

**Review by hervebutera — COMMENTED** [review]
@BiGelio , why is it that you've removed the babel dependencies added by Duncan's PR and the es 6 codes?

**Comment by bigelio** [comment]
I think i did rebase only with incoming changes

**Review by kipropbrian — APPROVED** [review]
Good job @BiGelio, this looks good. Remember to ensure that guys update the swagger  documentation and that it works on heroku

**Comment by bigelio** [comment]
Yeah it works

**Comment by kipropbrian** [comment]
Do you have the link to it on heroku?

**Comment by kipropbrian** [comment]
Could you update the readme.md file and add a link to heroku, plus the link to your swagger

**Comment by bigelio** [comment]
I don't have the link to it on heroku but the way i did it , It will automatically use base url.

**Comment by kipropbrian** [comment]
Here is the link to heroku https://strikers2020.herokuapp.com/

**Comment by bigelio** [comment]
My be that my feature is not deployed on heroku.

**Comment by kipropbrian** [comment]
Ok can you edit the readme.md for now. Just add the link to heroku and for swagger

**Comment by bigelio** [comment]
Let me add link for heroku also

**Pull request merged**
