### PR TITLE
#175636831 Configure ESLINT 

### PR DESCRIPTION
**Pull request by MChristian00**
####  What does this PR do?
Configure ESLINT to ensure our files meet the standard linting styles.
#### Description of Task to be completed?
Add  .eslintrc.json file which is to contain the rules for linting.
Add rules, from pivotal tracker story, for linting our project codebase files.
#### How should this be manually tested?
run `git clone https://github.com/atlp-rwanda/tech-strikers-bn-backend.git`
run `cd directory tech-strikers-bn-backend`
run ` ./node_modules/.bin/eslint src/index.js`
#### What are the relevant pivotal tracker stories?
[#175636831](https://www.pivotaltracker.com/story/show/175636831)

### CODE REVIEW

**Review by Duncanwar — COMMENTED** [review]
According to me. Your eslint rules are well set

**Comment by Duncanwar** [comment]
> #### What does this PR do?
> Configure ESLINT
> 
> #### Description of Task to be completed?
> Install packages
> Add rules for linting
> 
> #### How should this be manually tested?
> clone the repo
> cd into directory tech-strikers-bn-backend
> run `npm install`
> run ` ./node_modules/.bin/eslint src/index.js`
> 
> #### What are the relevant pivotal tracker stories?
> [#175636831](https://www.pivotaltracker.com/story/show/175636831)

**Comment by Duncanwar** [comment]
You can give more details about what your pull request do and checking it manually.

**Comment by hervebutera** [comment]
Maybe if you would be more descriptive as Maiyo advised, it would be better

**Review by Duncanwar — APPROVED** [review]
It is nice

**Review by hervebutera — APPROVED** [review]
Everything looks okay, it may be merged

**Review by Duncanwar — APPROVED** [review]

**Pull request merged**
